1. Импорт библиотеки NumPy с общепринятым сокращением.

In [4]:
import numpy as np

2. Примеры создания массивов:
   - из обычных списков;
   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.

In [ ]:
# Создание обычных списков

arr = np.array([1,2,3]) # Обычный список
arr2 = np.array([[1,2,3], [4,5,6]]) # Двумерный массив

# Использование функций

arrZeros = np.zeros((3,4)) # Будет матрица 3 на 4 заполненая нулями
arrOnes = np.ones((6,2)) # Будет матрица 6 на 2 заполненая единицами
arrArange = np.arange(2, 10, 2) # Будет список с 2 (включая) по 10 (не включая) с шагом 2

3. Демонстрация атрибутов:
   - вывод формы (shape) и типа данных (dtype) для одного из массивов.

In [ ]:
print(arr2.shape) # Выводим форму массива
print(arr2.dtype) # Получаем тип данных массива

(2, 3)
int64


4. Примеры индексирования и срезов:
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.

In [ ]:
element = arr2[0, 2] # Получение отдельного элемента
subarray = arr2[0:2, 2:3] # Извлечение подмассива с помощью среза (Мы достаем 1 и 2 строки, 3 столбца)

array([[3],
       [6]])

5. Примеры векторных операций и базовых статистик:
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.

In [32]:
x = np.array([1,2,3])
y = np.array([7,8,9])
print(x + y) # Поэлеметное сложение
print(y - x) # Поэлементное вычитание
print(x * y) # Поэлементное умножение

print(np.mean(y)) # Срденяя величина массива y
print(np.sum(x)) # Сумма массива x
print(np.max(y)) # Поиск максимального элемента массива y

[ 8 10 12]
[6 6 6]
[ 7 16 27]
8.0
6
9
